'use client'

import type { AnalysisResult } from '@/types/analysis'
import { formatTime } from '@/lib/audioAnalysis'

interface Props {
  result: AnalysisResult
  fileName: string
}

const SEVERITY_COLOR: Record<string, string> = {
  CRITICAL: '#dd6974',
  IMPORTANT: '#e8af34',
  MINOR: '#4f98a3',
  VALIDATION: '#6daa45',
}

const SEVERITY_LABEL: Record<string, string> = {
  CRITICAL: 'Critical',
  IMPORTANT: 'Important',
  MINOR: 'Minor',
  VALIDATION: 'Good',
}

function fmtCost(usd: number) {
  if (usd < 0.001) return '<$0.001'
  return `$${usd.toFixed(4)}`
}

export default function ExportPDF({ result, fileName }: Props) {
  function exportPDF() {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    const trackName = fileName.replace(/\.[^.]+$/, '')

    const feedbackRows = result.feedbackItems.map((item) => {
      const color = SEVERITY_COLOR[item.severity] ?? '#888'
      const label = SEVERITY_LABEL[item.severity] ?? item.severity
      const ts = item.timestamp != null ? `<span style="font-family:monospace;font-size:11px;color:#888;"> @ ${formatTime(item.timestamp)}</span>` : ''
      return `
        <div style="margin-bottom:16px;padding:14px 16px;border-radius:10px;border:1px solid ${color}22;background:${color}0a;">
          <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;">
            <span style="font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:${color};">${label}</span>${ts}
          </div>
          <p style="margin:0 0 4px;font-size:11px;color:#999;">${item.observation}</p>
          <p style="margin:0;font-size:13px;color:#e0ddd8;line-height:1.6;">${item.feedback}</p>
        </div>
      `
    }).join('')

    const metaPills = [
      result.bpm ? `${result.bpm} BPM` : null,
      result.key ?? null,
      formatTime(result.durationSeconds),
      result.costEstimate ? `${fmtCost(result.costEstimate.totalCostUsd)} · ${result.costEstimate.model}` : null,
    ].filter(Boolean).map((t) =>
      `<span style="display:inline-block;margin:0 4px 4px 0;padding:3px 10px;border-radius:99px;border:1px solid rgba(255,255,255,0.12);font-family:monospace;font-size:11px;color:#bbb;">${t}</span>`
    ).join('')

    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>MixLens — ${trackName}</title>
<style>
  @import url('https://api.fontshare.com/v2/css?f[]=satoshi@400,500,700&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Satoshi', 'Helvetica Neue', sans-serif; background: #0e0e0f; color: #e8e6e1; padding: 48px 56px; max-width: 900px; margin: 0 auto; }
  @media print {
    body { background: #fff; color: #111; padding: 32px 40px; }
    .no-print { display: none !important; }
    a { color: inherit; text-decoration: none; }
  }
</style>
</head>
<body>
  <!-- Header -->
  <div style="display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:32px;padding-bottom:20px;border-bottom:1px solid rgba(255,255,255,0.1);">
    <div>
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;">
        <span style="font-size:13px;font-weight:700;letter-spacing:.04em;color:#4f98a3;">MIXLENS</span>
        <span style="font-size:11px;color:#555;font-family:monospace;">v0.6</span>
      </div>
      <h1 style="font-size:22px;font-weight:700;color:#f0eee9;margin-bottom:4px;">${trackName}</h1>
      <p style="font-size:12px;color:#666;">${date}</p>
    </div>
    <div style="text-align:right;">
      <p style="font-size:11px;color:#555;">Analysis Report</p>
    </div>
  </div>

  <!-- Meta pills -->
  <div style="margin-bottom:24px;">${metaPills}</div>

  <!-- Summary -->
  <div style="margin-bottom:28px;padding:16px 20px;border-radius:12px;border:1px solid rgba(255,255,255,0.08);background:rgba(255,255,255,0.03);">
    <p style="font-size:10px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#555;margin-bottom:8px;">✦ Overall Summary</p>
    <p style="font-size:14px;color:#ccc;line-height:1.7;">${result.summary}</p>
  </div>

  <!-- Feedback -->
  <div style="margin-bottom:8px;">
    <p style="font-size:10px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#555;margin-bottom:14px;">Feedback Items</p>
    ${feedbackRows}
  </div>

  <!-- Footer -->
  <div style="margin-top:40px;padding-top:16px;border-top:1px solid rgba(255,255,255,0.06);display:flex;justify-content:space-between;align-items:center;">
    <span style="font-size:11px;color:#444;">Generated by MixLens · mixlens.jordy.beer</span>
    <span style="font-size:11px;color:#444;font-family:monospace;">${result.feedbackItems.length} feedback items</span>
  </div>

  <div class="no-print" style="margin-top:32px;text-align:center;">
    <button onclick="window.print()" style="padding:10px 24px;border-radius:8px;border:none;background:#4f98a3;color:#fff;font-size:13px;font-weight:600;cursor:pointer;font-family:inherit;">Print / Save as PDF</button>
  </div>
</body>
</html>`

    const win = window.open('', '_blank')
    if (win) {
      win.document.write(html)
      win.document.close()
    }
  }

  return (
    <button
      onClick={exportPDF}
      className="flex items-center gap-2 px-4 py-2.5 rounded-lg border border-white/10 bg-white/5 hover:bg-white/10 hover:border-white/20 transition-all text-sm text-white/70 hover:text-white"
    >
      <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M2 10v2h10v-2M7 1v7M4 5l3 3 3-3"/>
      </svg>
      Export as PDF
    </button>
  )
}
